[package]
name = "gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.28.0", features = ["macros", "rt-multi-thread"] }
anyhow = "1.0.71"
reqwest = "0.11.17"
thiserror = "1.0.40"
swc_atoms = "0.5.3"
swc_common = "0.31.5"
swc_ecma_parser = "0.133.12"
swc_ecma_ast = "0.103.5"
swc_ecma_codegen = "0.138.15"
once_cell = "1.17.1"
string_cache = "0.8.7"
