[package]
name = "gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
anyhow = "1.0.69"
reqwest = "0.11.14"
thiserror = "1.0.39"
swc_atoms = "0.4.39"
swc_common = "0.29.37"
swc_ecma_parser = "0.130.3"
swc_ecma_ast = "0.100.1"
swc_ecma_codegen = "0.135.4"
once_cell = "1.17.1"
string_cache = "0.8.7"
