[package]
name = "gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
anyhow = "1.0.86"
reqwest = "0.11.27"
thiserror = "1.0.63"
swc_atoms = "0.5.9"
swc_common = "0.31.22"
swc_ecma_parser = "0.137.16"
swc_ecma_ast = "0.107.8"
swc_ecma_codegen = "0.142.18"
once_cell = "1.19.0"
string_cache = "0.8.7"
